// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfqwvxlwyiuqkxlswswr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcXd2eGx3eWl1cWt4bHN3c3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjA3NTcsImV4cCI6MjA2NTE5Njc1N30.lnCBIeLZbirb6j23kuqqX48HPkSAPPAzNofdcbBX6VE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);